#!/usr/bin/env bash
# Builds vendor/ccharts_abi.c into a standalone WebAssembly module and embeds
# it in src/wasm-binary.js as base64.
#
# The result imports nothing but five wasi_snapshot_preview1 stdio functions
# (pulled in by snprintf/fprintf); src/index.js stubs them, so the module runs
# unchanged in Node, Deno, Bun and browsers with no loader, no fetch and no
# bundler configuration.
#
#   ./scripts/build.sh            # needs emcc on PATH (or EMCC=/path/to/emcc)
set -euo pipefail

cd "$(dirname "$0")/.."
EMCC="${EMCC:-emcc}"

if ! command -v "${EMCC}" > /dev/null 2>&1; then
  echo "emcc not found. Install emscripten or set EMCC=/path/to/emcc" >&2
  exit 1
fi

EXPORTS='["_ccharts_from_arrays","_ccharts_parse_json","_ccharts_parse_csv",'
EXPORTS+='"_ccharts_data_len","_ccharts_data_free","_ccharts_line",'
EXPORTS+='"_ccharts_candle","_ccharts_string_free","_ccharts_color",'
EXPORTS+='"_ccharts_error_message","_ccharts_version","_ccharts_max_dim",'
EXPORTS+='"_ccharts_max_cells","_malloc","_free"]'

mkdir -p build
"${EMCC}" vendor/ccharts_abi.c -Ivendor \
  -Oz -std=c99 \
  --no-entry \
  -sSTANDALONE_WASM=1 \
  -sALLOW_MEMORY_GROWTH=1 \
  -sEXPORTED_FUNCTIONS="${EXPORTS}" \
  -o build/ccharts.wasm

node --input-type=module -e '
import { readFileSync, writeFileSync } from "node:fs";
const wasm = readFileSync("build/ccharts.wasm");
const banner = `// Generated by scripts/build.sh from vendor/ccharts_abi.c — do not edit.
// The WebAssembly module, base64-encoded so the package is a single file that
// needs no fetch, no loader and no bundler configuration.
`;
writeFileSync("src/wasm-binary.js",
  banner + "export const wasmBase64 =\n  \"" + wasm.toString("base64") + "\";\n");
console.log("wasm:", wasm.length, "bytes ->", "src/wasm-binary.js");
'
