#!/usr/bin/env python3
"""Copy the C sources into each binding's vendor location.

Go requires cgo's .c files to sit inside the package directory, and
`cargo package` only ships files from within the crate — so every publishable
binding needs its own copy of ccharts.h and the ABI. Copies are generated,
never edited by hand:

    python3 scripts/sync_sources.py            # refresh the copies
    python3 scripts/sync_sources.py --check    # fail if any copy is stale

CI runs --check, which is the same drift guard scripts/gen_golden.py --check
applies to the rendered output. Destinations whose binding does not exist yet
are skipped, so this stays correct as bindings land one phase at a time.
"""

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SOURCES = ["ccharts.h", "abi/ccharts_abi.h", "abi/ccharts_abi.c"]

# binding root -> directory the copies live in, relative to that root.
DESTINATIONS = {
    # cgo needs the sources in the package directory itself.
    "bindings/go": "ccharts",
    # cargo packages only what is inside the crate.
    "bindings/rust": "vendor",
    "bindings/js": "vendor",
    "bindings/dotnet": "vendor",
    "bindings/java": "vendor",
}

BANNER = ("/* Generated by scripts/sync_sources.py from %s — do not edit.\n"
          " * Change the original and re-run the script. */\n")


def targets():
    for binding, subdir in sorted(DESTINATIONS.items()):
        root = os.path.join(ROOT, binding)
        if not os.path.isdir(root):
            continue          # binding not implemented yet
        yield binding, os.path.join(root, subdir)


def content_for(source):
    with open(os.path.join(ROOT, source), "rb") as f:
        body = f.read()
    return BANNER.encode("utf-8") % source.encode("utf-8") + body


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report stale copies instead of refreshing them")
    args = ap.parse_args()

    payload = {src: content_for(src) for src in SOURCES}
    stale, copied, seen_any = [], 0, False

    for _binding, dest in targets():
        seen_any = True
        if not args.check:
            os.makedirs(dest, exist_ok=True)
        for src, body in payload.items():
            path = os.path.join(dest, os.path.basename(src))
            if args.check:
                if not os.path.exists(path):
                    stale.append("%s: missing" % os.path.relpath(path, ROOT))
                elif open(path, "rb").read() != body:
                    stale.append("%s: out of date" % os.path.relpath(path, ROOT))
            else:
                with open(path, "wb") as f:
                    f.write(body)
                copied += 1

    if not seen_any:
        print("no bindings to sync yet")
        return 0

    if args.check:
        if stale:
            for line in stale:
                print("DRIFT: %s" % line, file=sys.stderr)
            print("run: python3 scripts/sync_sources.py", file=sys.stderr)
            return 1
        print("vendored sources are up to date")
        return 0

    print("synced %d file(s)" % copied)
    return 0


if __name__ == "__main__":
    sys.exit(main())
